export const chicagoData = {
  type: "FeatureCollection",
  query: ["chicago"],
  features: [
    {
      id: "place.59328748",
      type: "Feature",
      place_type: ["place"],
      relevance: 1,
      properties: {
        wikidata: "Q1297",
        mapbox_id: "dXJuOm1ieHBsYzpBNGxJN0E",
      },
      text: "Chicago",
      place_name: "Chicago, Illinois, United States",
      bbox: [-87.869226, 41.644286, -87.509753018, 42.034895347],
      center: [-87.624421, 41.875562],
      geometry: {
        type: "Point",
        coordinates: [-87.624421, 41.875562],
      },
      context: [
        {
          id: "district.5162732",
          wikidata: "Q108418",
          mapbox_id: "dXJuOm1ieHBsYzpUc2Jz",
          text: "Cook County",
        },
        {
          id: "region.17644",
          short_code: "US-IL",
          wikidata: "Q1204",
          mapbox_id: "dXJuOm1ieHBsYzpST3c",
          text: "Illinois",
        },
        {
          id: "country.8940",
          short_code: "us",
          wikidata: "Q30",
          mapbox_id: "dXJuOm1ieHBsYzpJdXc",
          text: "United States",
        },
      ],
    },
    {
      id: "poi.867583448328",
      type: "Feature",
      place_type: ["poi"],
      relevance: 1,
      properties: {
        foursquare: "4a5a77a4f964a52062ba1fe3",
        wikidata: "Q213717",
        landmark: true,
        address: "10000 W O'Hare Ave",
        category: "airport",
        maki: "airport",
      },
      text: "Chicago O'Hare International Airport",
      place_name:
        "Chicago O'Hare International Airport, 10000 W O'Hare Ave, Rosemont, Illinois 60666, United States",
      center: [-87.9029655, 41.977584],
      geometry: {
        coordinates: [-87.9029655, 41.977584],
        type: "Point",
      },
      context: [
        {
          id: "postcode.208441068",
          mapbox_id: "dXJuOm1ieHBsYzpER3lPN0E",
          text: "60666",
        },
        {
          id: "place.284002540",
          wikidata: "Q1191401",
          mapbox_id: "dXJuOm1ieHBsYzpFTzJJN0E",
          text: "Rosemont",
        },
        {
          id: "district.5162732",
          wikidata: "Q108418",
          mapbox_id: "dXJuOm1ieHBsYzpUc2Jz",
          text: "Cook County",
        },
        {
          id: "region.17644",
          short_code: "US-IL",
          wikidata: "Q1204",
          mapbox_id: "dXJuOm1ieHBsYzpST3c",
          text: "Illinois",
        },
        {
          id: "country.8940",
          short_code: "us",
          wikidata: "Q30",
          mapbox_id: "dXJuOm1ieHBsYzpJdXc",
          text: "United States",
        },
      ],
    },
    {
      id: "poi.472446423802",
      type: "Feature",
      place_type: ["poi"],
      relevance: 1,
      properties: {
        wikidata: "Q1061437",
        category: "airport",
        landmark: true,
        address: "5700 S Cicero Ave",
        foursquare: "4a198a3ef964a520237a1fe3",
        maki: "airport",
      },
      text: "Chicago Midway International Airport (MDW)",
      place_name:
        "Chicago Midway International Airport (MDW), 5700 S Cicero Ave, Chicago, Illinois 60638, United States",
      matching_text: "Şikago Midway Uluslararası Havaalanı",
      matching_place_name:
        "Şikago Midway Uluslararası Havaalanı, 5700 S Cicero Ave, Chicago, Illinois 60638, United States",
      center: [-87.747394, 41.786872],
      geometry: {
        coordinates: [-87.747394, 41.786872],
        type: "Point",
      },
      context: [
        {
          id: "postcode.208260844",
          mapbox_id: "dXJuOm1ieHBsYzpER25PN0E",
          text: "60638",
        },
        {
          id: "place.59328748",
          wikidata: "Q1297",
          mapbox_id: "dXJuOm1ieHBsYzpBNGxJN0E",
          text: "Chicago",
        },
        {
          id: "district.5162732",
          wikidata: "Q108418",
          mapbox_id: "dXJuOm1ieHBsYzpUc2Jz",
          text: "Cook County",
        },
        {
          id: "region.17644",
          short_code: "US-IL",
          wikidata: "Q1204",
          mapbox_id: "dXJuOm1ieHBsYzpST3c",
          text: "Illinois",
        },
        {
          id: "country.8940",
          short_code: "us",
          wikidata: "Q30",
          mapbox_id: "dXJuOm1ieHBsYzpJdXc",
          text: "United States",
        },
      ],
    },
    {
      id: "neighborhood.113257708",
      type: "Feature",
      place_type: ["neighborhood"],
      relevance: 1,
      properties: {
        mapbox_id: "dXJuOm1ieHBsYzpCc0FzN0E",
      },
      text: "Chicago Lawn",
      place_name: "Chicago Lawn, Chicago, Illinois, United States",
      bbox: [-87.722961426, 41.757160187, -87.676429749, 41.786598206],
      center: [-87.696441, 41.775033],
      geometry: {
        type: "Point",
        coordinates: [-87.696441, 41.775033],
      },
      context: [
        {
          id: "postcode.208195308",
          mapbox_id: "dXJuOm1ieHBsYzpER2pPN0E",
          text: "60629",
        },
        {
          id: "place.59328748",
          wikidata: "Q1297",
          mapbox_id: "dXJuOm1ieHBsYzpBNGxJN0E",
          text: "Chicago",
        },
        {
          id: "district.5162732",
          wikidata: "Q108418",
          mapbox_id: "dXJuOm1ieHBsYzpUc2Jz",
          text: "Cook County",
        },
        {
          id: "region.17644",
          short_code: "US-IL",
          wikidata: "Q1204",
          mapbox_id: "dXJuOm1ieHBsYzpST3c",
          text: "Illinois",
        },
        {
          id: "country.8940",
          short_code: "us",
          wikidata: "Q30",
          mapbox_id: "dXJuOm1ieHBsYzpJdXc",
          text: "United States",
        },
      ],
    },
    {
      id: "place.59345132",
      type: "Feature",
      place_type: ["place"],
      relevance: 1,
      properties: {
        wikidata: "Q578277",
        mapbox_id: "dXJuOm1ieHBsYzpBNG1JN0E",
      },
      text: "Chicago Heights",
      place_name: "Chicago Heights, Illinois, United States",
      bbox: [-87.674425, 41.484209, -87.586310806, 41.542563],
      center: [-87.635708, 41.506283],
      geometry: {
        type: "Point",
        coordinates: [-87.635708, 41.506283],
      },
      context: [
        {
          id: "district.5162732",
          wikidata: "Q108418",
          mapbox_id: "dXJuOm1ieHBsYzpUc2Jz",
          text: "Cook County",
        },
        {
          id: "region.17644",
          short_code: "US-IL",
          wikidata: "Q1204",
          mapbox_id: "dXJuOm1ieHBsYzpST3c",
          text: "Illinois",
        },
        {
          id: "country.8940",
          short_code: "us",
          wikidata: "Q30",
          mapbox_id: "dXJuOm1ieHBsYzpJdXc",
          text: "United States",
        },
      ],
    },
  ],
  attribution:
    "NOTICE: © 2023 Mapbox and its suppliers. All rights reserved. Use of this data is subject to the Mapbox Terms of Service (https://www.mapbox.com/about/maps/). This response and the information it contains may not be retained. POI(s) provided by Foursquare.",
};
